export const ISINSTANCEAVAILABLE = 'ISINSTANCEAVAILABLE';
export const ISRANGEAVAILABLE = 'ISRANGEAVAILABLE';
export const UPDATECOLUMNDATA = 'UPDATECOLUMNDATA';
export const ISEXPORTINSTANCEAVAILABLE = 'ISEXPORTINSTANCEAVAILABLE';
export const ISDATASELECTIONAVAILABLE = 'ISDATASELECTIONAVAILABLE';
export const DIALOGINSTANCE = 'DIALOGINSTANCE'
export const SHOWCALCULATIONS = 'SHOWCALCULATIONS';
export const EXPORTDATASELECTIONCOLUMNS = 'EXPORTDATASELECTIONCOLUMNS';
export const EXPORTDATASELECTIONSTEPWISE = 'EXPORTDATASELECTIONSTEPWISE';
export const ISUNDODATAVAILABLE = 'ISUNDODATAVAILABLE';
export const ISREDODATAVAILABLE = 'ISREDODATAVAILABLE';
export const UPDATEROWINDEX = 'UPDATEROWINDEX';
export const ISWIZARDOPEN = 'ISWIZARDOPEN';
export const EXPORTSTATUSLABELVALUES = 'EXPORTSTATUSLABELVALUES';
export const EXPORTDATASELECTIONSTEPWISETABLE = 'EXPORTDATASELECTIONSTEPWISETABLE';
export const UPDATEREDISTEST = 'UPDATEREDISTEST';
export const UPDATEFREQLIST = 'UPDATEFREQLIST';
export const UPDATEFREQ = 'UPDATEFREQ';



