
export const STOREWORKSHEET = 'STOREWORKSHEET';
export const REMOVEWORKSHEET = 'REMOVEWORKSHEET';

export const STOREGRAPH = 'STOREGRAPH';
export const REMOVEGRAPH = 'REMOVEGRAPH';

export const SETACTIVEWORKSHEET = 'SETACTIVEWORKSHEET';

export const CLEARNOTEBOOK = 'CLEARNOTEBOOK'

