export const ISOPENGRAPHICCELL = 'ISOPENGRAPHICCELL'
export const GRAPHICCELLUPDATE = 'GRAPHICCELLUPDATE'
export const GP_CELL_PLOTUPDATE = 'GP_CELL_PLOTUPDATE'
export const GRAPHICCELLRGBUPDATE  = 'GRAPHICCELLRGBUPDATE'