export const ISOPENTTEST = 'ISOPENTTEST';
export const ISOPENPAIREDTTEST = 'ISOPENPAIREDTTEST';
export const ISOPENPROPORIONS = 'ISOPENPROPORIONS';
export const ISOPENANOVA = 'ISOPENANOVA';
export const ISOPENCHISQUARE = 'ISOPENCHISQUARE';
export const ISOPENCORRELATION = 'ISOPENCORRELATION';
export const ISCHISQUAREDATAVAILABLE = 'ISCHISQUAREDATAVAILABLE';