export const ISOPENDELROW = 'ISOPENDELROW';
export const ISOPENDELCOL = 'ISOPENDELCOL';
export const ISOPENSHIFTCELLLEFT = 'ISOPENSHIFTCELLLEFT';
export const ISOPENSHIFTCELLUP = 'ISOPENSHIFTCELLUP';
