export const ISOPENINSROW = 'ISOPENINSROW';
export const ISOPENINSCOL = 'ISOPENINSCOL';
export const ISOPENSHIFTCELLRIGHT = 'ISOPENSHIFTCELLRIGHT';
export const ISOPENSHIFTCELLDOWN = 'ISOPENSHIFTCELLDOWN';
