export const ISOPENPWTTEST = 'ISOPENPWTTEST';
export const ISOPENPWPAIREDTTEST = 'ISOPENPWPAIREDTTEST';
export const ISOPENPWPROPORIONS = 'ISOPENPWPROPORIONS';
export const ISOPENPWANOVA = 'ISOPENPWANOVA';
export const ISOPENPWCHISQUARE = 'ISOPENPWCHISQUARE';
export const ISOPENPWCORRELATION = 'ISOPENPWCORRELATION';