export const XYpair = "XYpair";
export const SingleX = "SingleX";
export const SingleY = "SingleY";
export const XManyY = "XManyY";
export const YManyX = "YManyX";
export const ManyX = "ManyX";
export const ManyY = "ManyY";
export const XCategory = "XCategory";
export const YCategory = "YCategory";
export const XYCategory = "XYCategory";
export const XYpairs = "XYpairs";
export const YXpairs = "YXpairs";
export const XYReplicate = "XYReplicate";
export const YReplicate = "YReplicate";
export const XManyYReplicate = "XManyYReplicate";
export const ManyYReplicate = "ManyYReplicate";
export const CategoryY = "CategoryY";
export const CategoryX = "CategoryX";
export const ThetaR = "ThetaR";
export const ThetaManyR = "ThetaManyR";
export const RManyTheta = "RManyTheta";
export const ManyR = "ManyR";
export const ManyTheta = "ManyTheta";
export const LabelManySeries = "LabelManySeries";
export const ManyLabel = "ManyLabel";
export const ManySeries = "ManySeries";
export const LabelManySeriesError = "LabelManySeriesError";
export const ManySeriesError = "ManySeriesError";
export const YXpair = "YXpair";
export const YXReplicate = "YXReplicate";
export const YManyXReplicate = "YManyXReplicate";
export const CategoryManyY = "CategoryManyY";
export const CategoryManyX = "CategoryManyX";
export const XYZTriplet = "XYZTriplet";
export const ManyZ = "ManyZ";
export const XYManyZ = "XYManyZ";
export const TernaryTriplets = "TernaryTriplets";
export const TernaryXYPairs = "TernaryXYPairs";
export const TernaryYZPairs = "TernaryYZPairs";
export const TernaryXZPairs = "TernaryXZPairs";
export const SingleColumn = "SingleColumn";
// export const ManyXReplicate = "ManyXReplicate";

export const typeList =
[
  {id: "1", value:"XYpair", title: "XYpair"},
  {id: "2", value:"SingleX", title: "SingleX"},
  {id: "3", value:"SingleY", title: "SingleY"},
  {id: "4", value:"XManyY", title: "XManyY"},
  {id: "5", value:"YManyX", title: "YManyX"},
  {id: "6", value:"ManyX", title: "ManyX"},
  {id: "7", value:"ManyY", title: "ManyY"},
  {id: "8", value:"XCategory", title: "XCategory"},
  {id: "9", value:"YCategory", title: "YCategory"},
  {id: "10", value:"XYCategory", title: "XYCategory"},
  {id: "11", value:"XYpairs", title: "XYpairs"},
  {id: "12", value:"YXpairs", title: "YXpairs"},
  {id: "13", value:"XYReplicate", title: "XYReplicate"},
  {id: "14", value:"YReplicate", title: "YReplicate"},
  {id: "15", value:"XManyYReplicate", title: "XManyYReplicate"},
  {id: "16", value:"ManyYReplicate", title: "ManyYReplicate"},
  {id: "17", value:"CategoryY", title: "CategoryY"},
  {id: "18", value:"CategoryX", title: "CategoryX"},
  {id: "19", value:"ThetaR", title: "ThetaR"},
  {id: "20", value:"ThetaManyR", title: "ThetaManyR"},
  {id: "21", value:"RManyTheta", title: "RManyTheta"},
  {id: "22", value:"ManyR", title: "ManyR"},
  {id: "23", value:"ManyTheta", title: "ManyTheta"},
  {id: "24", value:"LabelManySeries", title: "LabelManySeries"},
  {id: "25", value:"ManyLabel", title: "ManyLabel"},
  {id: "26", value:"ManySeries", title: "ManySeries"},
  {id: "27", value:"LabelManySeriesError", title: "LabelManySeriesError"},
  {id: "28", value:"ManySeriesError", title: "ManySeriesError"},
  {id: "29", value:"YXpair", title: "YXpair"},
  {id: "30", value:"YXReplicate", title: "YXReplicate"},
  {id: "31", value:"YManyXReplicate", title: "YManyXReplicate"},
  {id: "32", value:"CategoryManyY", title: "CategoryManyY"},
  {id: "33", value:"CategoryManyX", title: "CategoryManyX"},
  {id: "34", value:"XYZTriplet", title: "XYZTriplet"},
  {id: "35", value:"ManyZ", title: "ManyZ"},
  {id: "36", value:"XYManyZ", title: "XYManyZ"},
  {id: "37", value:"TernaryTriplets", title: "TernaryTriplets"},
  {id: "38", value:"TernaryXYPairs", title: "TernaryXYPairs"},
  {id: "39", value:"TernaryYZPairs", title: "TernaryYZPairs"},
  {id: "40", value:"TernaryXZPairs", title: "TernaryXZPairs"},
  {id: "41", value:"SingleColumn", title: "SingleColumn"},
  // {id: "42", value:"ManyXReplicate", title: "ManyXReplicate"},
];
