export const IS_STATUSBAR_DISPLAY = 'IS_STATUSBAR_DISPLAY';
export const IS_NOTEBOOKMANAGER_DISPLAY = 'IS_NOTEBOOKMANAGER_DISPLAY';
export const IS_NOTEBOOKMANAGER_DISPLAY2 = 'IS_NOTEBOOKMANAGER_DISPLAY2';
export const IS_GRAPHGALLERY_DISPLAY = 'IS_GRAPHGALLERY_DISPLAY';
export const IS_TEMPLATE_DISPLAY = 'IS_TEMPLATE_DISPLAY';
export const IS_WORKSHEETDIALOG_HIDE = 'IS_WORKSHEETDIALOG_HIDE';
export const IS_LOADER_DISPLAY = 'IS_LOADER_DISPLAY';

