export const ISOPENQUICKTRANSFORM = 'ISOPENQUICKTRANSFORM'
export const ISOPENUSERDEFINED = 'ISOPENUSERDEFINED'
export const ISOPENEQUATION = 'ISOPENEQUATION'
export const SETSELECTEDRANGE = 'SETSELECTEDRANGE'