export const ISOPTIONS = 'ISOPTIONS'
export const OPTIONSUPDATE = 'OPTIONSUPDATE'
export const ISEXIT = 'ISEXIT'
export const OPTIONSUPDATECOLLECTION = 'OPTIONSUPDATECOLLECTION'
export const SHOWPROPERTIESPANE = 'SHOWPROPERTIESPANE';
export const ENABLETOOLBAR = 'ENABLETOOLBAR';